title: 実践 Docker
summary:
  この本は１年ほど前に公開した Docker の本をブラッシュアップした本になります。


  https://zenn.dev/suzuki_hoge/books/2021-04-docker-picture-60fbe950136be9c7ad85


  先の本は、完全に初心者だった僕自身が学ぶ過程で欲しかった内容をまとめた本でした。

  本を書く過程で僕自身は深い学びを得られましたが、今見返すと内容がコマンドそのものに寄りすぎていたり、試行錯誤の過程まで記してあり冗長だったりすると感じています。


  この本ではそれらを改善し、コンテナ型仮想化の基礎知識を軽く学ぶことで、Docker の基礎知識を効率よく学べるようにしました。


  最後まで読み進めると、学んだ Docker の基礎知識をいろいろなコマンドや Docker Compose で脚色しながら、複数のコンテナにより構成されるサンプルアプリケーションを構築できます。


  この本はソフトウェアエンジニアが Docker で開発環境を構築するときに必要になる基礎知識とコマンドを図解し、今後は自力で Docker を用いた開発環境の構築が行えるようになることを目指します。

topics: [ "docker", "dockercompose", "初心者" ]
published: false
price: 0
toc_depth: 2
chapters:
  - 1-1-readme
  - 1-2-virtualization
  - 1-3-docker
  - 2-1-points
  - 2-2-container-basic-operation
  - 2-3-container-boot
  - 2-4-container-status
  - 2-5-container-state
  - 2-6-container-exec
  - 2-7-image
  - 2-8-dockerfile
  - 3-1-summary
  - 3-2-image
  - 3-3-run
  - 3-4-debug
  - 3-5-bind-mount
  - 3-6-volume
  - 3-7-publish
  - 3-8-network
  - 3-9-docker-compose
  - 3-10-trouble-shooting
